package: gerrit-code-review
jdk: JDK8
build_tool: maven-3.3.9
type: jar
stages:
  - test
  - deploy

step1:
    stage: test
    script:
        - mvn clean
        - mvn -B -U org.jacoco:jacoco-maven-plugin:prepare-agent verify
        - mvn -B -U org.jacoco:jacoco-maven-plugin:report

step2:
    stage: deploy
    script:
        - mvn -B -U install -Dmaven.test.skip=true
    is_package: true
    PackageType: hpi
    PackageFolder: target
