package: gerrit-code-review
jdk: 1.8
build_tool: maven-3.3.9
type: jar
is_dependent: false
job:
    script:
        - mvn -B -U clean install -Dmaven.test.skip=true
    pkgType: jar
    pkgFolder: target
